language: python
python:
  - 3.5
  - 3.6
  - pypy3
matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: true
install:
  - pip install tox_travis coveralls
script:
  - tox
after_success:
    - coveralls
cache: pip

